#! /bin/sh
# _                                          
#| |                                         
#| |__  ___ _ ____      ___ __ ___  _ __ ___ 
#| '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#| |_) \__ \ |_) \ V  V /| | | | | | | | (__ 
#|_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#          | |                               
#          |_| part of github.com/nockey/Dots 

# auto start

sxhkd &

light-locker &

picom &

dunst &

xrdb ~/.xresources &

~/.config/polybar/launch.sh &

~/.fehbg &

# configuration

xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V

bspc config border_width        3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#2C363F"
bspc config focused_border_coler "#647D90"

